services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 5173:5173

  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: "service_healthy"
    env_file:
      docker.env

  database:
    image: postgis/postgis
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - docker.env
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost || exit 1"]
       interval: 10s
       timeout: 5s
       retries: 5

  adminer:
    image: adminer
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pepa-linha

volumes:
  postgres_data:
