services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 5173:5173

  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - 3000:3000

  database:
    image: postgis/postgis
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - docker.env

  adminer:
    image: adminer
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pepa-linha

volumes:
  postgres_data:
